"""add_detailed_token_usage_columns

Revision ID: 34059e7db266
Revises: 006
Create Date: 2026-05-11 13:40:32.372771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34059e7db266'
down_revision: Union[str, Sequence[str], None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversions', sa.Column('input_text_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversions', sa.Column('output_text_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversions', sa.Column('input_audio_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversions', sa.Column('output_audio_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversions', sa.Column('summary_input_tokens', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversions', sa.Column('summary_output_tokens', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversions', 'summary_output_tokens')
    op.drop_column('conversions', 'summary_input_tokens')
    op.drop_column('conversions', 'output_audio_tokens')
    op.drop_column('conversions', 'input_audio_tokens')
    op.drop_column('conversions', 'output_text_tokens')
    op.drop_column('conversions', 'input_text_tokens')
    # ### end Alembic commands ###
